-- =============================================================================
-- CRIAÇÃO DAS TABELAS PARA HISTÓRICO DE ACESSOS DA VITRINE
-- Execute este script no editor SQL do Supabase
-- =============================================================================

-- Tabela principal de acessos detalhados
CREATE TABLE IF NOT EXISTS vitrine_acessos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vitrine_id bigint NOT NULL REFERENCES vitrine(id) ON DELETE CASCADE,
  data_acesso date DEFAULT CURRENT_DATE,
  hora_acesso time DEFAULT CURRENT_TIME,
  ip_hash text,
  dispositivo text,
  fonte text,
  created_at timestamptz DEFAULT now()
);

-- Index para consultas rápidas
CREATE INDEX IF NOT EXISTS idx_vitrine_acessos_vitrine_id ON vitrine_acessos(vitrine_id);
CREATE INDEX IF NOT EXISTS idx_vitrine_acessos_data ON vitrine_acessos(data_acesso);
CREATE INDEX IF NOT EXISTS idx_vitrine_acessos_data_vitrine ON vitrine_acessos(data_acesso, vitrine_id);

-- =============================================================================
-- FUNCTION PARA REGISTRAR ACESSO (chamar via API)
-- =============================================================================

CREATE OR REPLACE FUNCTION registrar_acesso_vitrine(
  p_vitrine_id bigint,
  p_ip text DEFAULT NULL,
  p_dispositivo text DEFAULT NULL,
  p_fonte text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO vitrine_acessos (vitrine_id, ip_hash, dispositivo, fonte)
  VALUES (p_vitrine_id, p_ip, p_dispositivo, p_fonte);
  
  UPDATE vitrine
  SET acessos = COALESCE(acessos, 0) + 1
  WHERE id = p_vitrine_id;
END;
$$;

-- =============================================================================
-- FUNCTION PARA BUSCAR ESTATÍSTICAS DE ACESSO POR PERÍODO
-- =============================================================================

CREATE OR REPLACE FUNCTION get_vitrine_acessos_periodo(
  p_vitrine_id bigint,
  p_dias integer DEFAULT 30
)
RETURNS TABLE(
  data date,
  total integer
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  WITH datas AS (
    SELECT generate_series(
      CURRENT_DATE - (p_dias - 1),
      CURRENT_DATE,
      '1 day'::interval
    )::date AS data
  )
  SELECT 
    d.data,
    COALESCE(COUNT(v.id), 0)::integer AS total
  FROM datas d
  LEFT JOIN vitrine_acessos v 
    ON v.data_acesso = d.data AND v.vitrine_id = p_vitrine_id
  GROUP BY d.data
  ORDER BY d.data;
END;
$$;

-- =============================================================================
-- FUNCTION PARA BUSCAR TOP PRODUTOS POR ACESSOS
-- =============================================================================

CREATE OR REPLACE FUNCTION get_vitrine_top_acessos(
  p_dias integer DEFAULT 30,
  p_limit integer DEFAULT 10
)
RETURNS TABLE(
  id bigint,
  nome text,
  tipo text,
  acessos integer
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    v.id,
    v.name,
    v.tipo,
    COALESCE(v.acessos, 0)::integer AS acessos
  FROM vitrine v
  ORDER BY v.acessos DESC NULLS LAST
  LIMIT p_limit;
END;
$$;

-- =============================================================================
-- FUNCTION PARA BUSCAR ACESSOS POR CATEGORIA
-- =============================================================================

CREATE OR REPLACE FUNCTION get_vitrine_acessos_categoria(
  p_dias integer DEFAULT 30
)
RETURNS TABLE(
  categoria text,
  total integer
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  WITH produtos_categorias AS (
    SELECT 
      v.id,
      unnest(v.categorias)::text AS categoria,
      v.acessos
    FROM vitrine v
    WHERE v.categorias IS NOT NULL
  )
  SELECT 
    pc.categoria,
    COALESCE(SUM(pc.acessos), 0)::integer AS total
  FROM produtos_categorias pc
  GROUP BY pc.categoria
  ORDER BY total DESC;
END;
$$;

-- =============================================================================
-- RPC:Buscar todos os acessos por dia (para gráficos)
-- =============================================================================

CREATE OR REPLACE FUNCTION get_vitrine_acessos_diarios(
  p_dias integer DEFAULT 30
)
RETURNS TABLE(
  data text,
  dia integer,
  total integer
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  WITH datas AS (
    SELECT generate_series(
      CURRENT_DATE - (p_dias - 1),
      CURRENT_DATE,
      '1 day'::interval
    )::date AS data
  ), contagem AS (
    SELECT 
      v.data_acesso AS data,
      COUNT(*)::integer AS total
    FROM vitrine_acessos v
    WHERE v.data_acesso >= CURRENT_DATE - (p_dias - 1)
    GROUP BY v.data_acesso
  )
  SELECT 
    to_char(d.data, 'YYYY-MM-DD') AS data,
    EXTRACT(DAY FROM CURRENT_DATE - d.data)::integer AS dia,
    COALESCE(c.total, 0)::integer AS total
  FROM datas d
  LEFT JOIN contagem c ON c.data = d.data
  ORDER BY d.data;
END;
$$;

-- =============================================================================
-- ATUALIZAR CAMPO ACESSOS NA TABELA VITRINE (se não existir)
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'vitrine' AND column_name = 'acessos'
  ) THEN
    ALTER TABLE vitrine ADD COLUMN acessos integer DEFAULT 0;
  END IF;
END
$$;